# Site
repository: davidsivocha/resume
# favicon: images/favicon.ico

# Personal info
name: David Sivocha
title: Head of Software Engineering
email: david@sivocha.com
website: www.sivocha.com

# Social links
# twitter_username: facespics
github_username:  davidsivocha
# dribbble_username: jekyll
facebook_username: david.sivocha
# flickr_username: jekyll
instagram_username: daelach
linkedin_username: davidsivocha
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/Dave-Sivocha.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's David and I'm a senior platform engineer. As well as managing systems I also develop web apps. I have worked at a number of companies gaining teamwork and leadership skills and constantly learning new development and administration techniques.

  When I'm not working, or learning new techniques, I enjoy spending my free time <mark>running</mark>, <mark>reading</mark> or <mark>Blacksmithing</mark>. I'm also an avid amateur photographer.

  I am most skilled in: <mark>Laravel</mark> and <mark>AWS Management</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
# more_content: | # this will include new lines to allow paragraphs
#   Alongside my interests in networks and software engineering some of my other interests and hobbies are:
#   - Climbing
#   - Gaming
#   - Knitting

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
