# Site
repository: davidsivocha/resume
# favicon: images/favicon.ico

# Personal info
name: David Sivocha
title: Hands-on CTO | Engineering Leader | PHP & AWS Specialist
email: david@sivocha.com
website: www.sivocha.com

# Social links
# twitter_username: facespics
github_username:  davidsivocha
# dribbble_username: jekyll
facebook_username: david.sivocha
# flickr_username: jekyll
instagram_username: daelach
linkedin_username: davidsivocha
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/Dave-Sivocha.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name’s David and I’m a <mark>CTO</mark> and hands-on technology leader. I specialise in building and scaling engineering teams, developing high-performing software platforms, and shaping technical strategy that aligns with business growth. Alongside managing systems and software teams, I stay closely involved in code, architecture, and DevOps — ensuring technical excellence and operational stability across every layer of the stack.

  Over my career I’ve worked across multiple sectors, particularly <mark>FinTech</mark> and <mark>SaaS</mark>, leading teams across the UK, North America, and Asia. I’m passionate about mentoring engineers, driving <mark>Agile</mark> culture, and delivering robust, scalable systems in <mark>AWS</mark> and <mark>Laravel</mark>-based environments.

  When I’m not building platforms or leading teams, I enjoy <mark>running</mark>, <mark>reading</mark>, and <mark>Blacksmithing</mark>, and I’m also an avid amateur photographer.

  I am most skilled in: <mark>Laravel</mark>, <mark>AWS Management</mark>, and <mark>Technical Leadership</mark>


# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
# more_content: | # this will include new lines to allow paragraphs
#   Alongside my interests in networks and software engineering some of my other interests and hobbies are:
#   - Climbing
#   - Gaming
#   - Knitting

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
